@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package games.moegirl.fortyyears.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;