@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package games.moegirl.fortyyears.generator;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;