@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package games.moegirl.fortyyears.block;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;