@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package games.moegirl.fortyyears.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;